spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: https://eurekaserver-app-dd87242b5252.herokuapp.com

logging:
  level:
    "[com.netflix.eureka]": OFF
    "[com.netflix.discovery]": OFF
