spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: trip-service
          uri: lb://trip-service
          predicates:
            - Path=/trips/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/**
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/reviews/**

server:
  port: 8080

eureka:
  instance:
    hostname: api-gateway
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://eurekaserver-app-dd87242b5252.herokuapp.com/eureka/