spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: trip-service
          uri: lb://trip-service
          predicates:
            - Path=/trips/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/**
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/reviews/**
        - id: keycloak
          uri: http://localhost:8000
          predicates:
            - Path=/keycloak/**

server:
  port: 8080

eureka:
  instance:
    hostname: api-gateway
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
