const mockTransactions = [
  {
    id: 1,
    userName: "Sarah Chen",
    userInitials: "SC",
    type: "buying",
    status: "confirmed",
    statusText: "Confirmed",
    flightNumber: "UA 847",
    date: "2025-12-15T23:30:00Z", // Dec 15, 11:30 PM UTC
    departure: "LAX",
    arrival: "NRT",
    weight: "6kg",
    rate: "$12/kg",
    total: "$72",
  },
  {
    id: 2,
    userName: "Mike Rodriguez",
    userInitials: "MR",
    type: "selling",
    status: "awaiting_payment",
    statusText: "Pending confirmation",
    flightNumber: "AA 123",
    date: "2025-12-16T08:15:00Z", // Dec 16, 8:15 AM UTC
    departure: "JFK",
    arrival: "LHR",
    weight: "10kg",
    rate: "$8/kg",
    total: "$80",
  },
  {
    id: 3,
    userName: "Alex Thompson",
    userInitials: "AT",
    type: "selling",
    status: "waiting_for_response",
    statusText: "Reservation sent",
    flightNumber: "DL 456",
    date: "2025-12-20T06:45:00Z", // Dec 20, 6:45 AM UTC
    departure: "ATL",
    arrival: "CDG",
    weight: "8kg",
    rate: "$12/kg",
    total: "$96",
  },
  {
    id: 4,
    userName: "Emily Davis",
    userInitials: "ED",
    type: "buying",
    status: "completed",
    statusText: "Completed",
    flightNumber: "BA 789",
    date: "2025-12-10T15:30:00Z", // Dec 10, 3:30 PM UTC
    departure: "LHR",
    arrival: "JFK",
    weight: "5kg",
    rate: "$10/kg",
    total: "$50",
  },
  {
    id: 5,
    userName: "John Smith",
    userInitials: "JS",
    type: "buying",
    status: "payment_required",
    statusText: "Payment required",
    flightNumber: "AF 321",
    date: "2025-12-18T10:00:00Z", // Dec 18, 10:00 AM UTC
    departure: "CDG",
    arrival: "LAX",
    weight: "7kg",
    rate: "$9/kg",
    total: "$63",
  },
  {
    id: 6,
    userName: "Linda Johnson",
    userInitials: "LJ",
    type: "selling",
    status: "request_rejected",
    statusText: "Request rejected",
    flightNumber: "LH 654",
    date: "2025-12-22T17:15:00Z", // Dec 22, 5:15 PM UTC
    departure: "FRA",
    arrival: "ORD",
    weight: "9kg",
    rate: "$11/kg",
    total: "$99",
  },
  {
    id: 7,
    userName: "David Wilson",
    userInitials: "DW",
    type: "buying",
    status: "browse_listing",
    statusText: "Browsing listings",
    flightNumber: "SQ 888",
    date: "2025-12-25T01:00:00Z", // Dec 25, 1:00 AM UTC
    departure: "SIN",
    arrival: "SFO",
    weight: "12kg",
    rate: "$15/kg",
    total: "$180",
  },
  {
    id: 8,
    userName: "Sophia Martinez",
    userInitials: "SM",
    type: "selling",
    status: "cancelled",
    statusText: "Cancelled",
    flightNumber: "QF 12",
    date: "2025-12-30T21:45:00Z", // Dec 30, 9:45 PM UTC
    departure: "SYD",
    arrival: "LAX",
    weight: "4kg",
    rate: "$14/kg",
    total: "$56",
  },
  {
    id: 9,
    userName: "James Brown",
    userInitials: "JB",
    type: "buying",
    status: "reservation_received",
    statusText: "Confirmed",
    flightNumber: "EK 202",
    date: "2025-12-28T02:30:00Z", // Dec 28, 2:30 AM UTC
    departure: "DXB",
    arrival: "JFK",
    weight: "11kg",
    rate: "$13/kg",
    total: "$143",
  },
];

export default mockTransactions;
