const mockTransactions = [
  {
    id: 1,
    sellerName: "Sarah Chen",
    sellerId: 1,
    buyerName: "John Doe",
    buyerId: 2,
    initials: "SC",
    type: "buying",
    status: "confirmed",
    statusText: "Confirmed",
    flightNumber: "UA 847",
    dateDeparture: "2025-12-15T23:30:00Z",
    dateArrival: "2025-12-16T14:15:00Z",
    departureAirport: "LAX",
    arrivalAirport: "NRT",
    weight: 6,
    pricePerKg: 12,
    total: 72,
    conditions: "No special conditions",
  },
  {
    id: 2,
    sellerName: "Mike Rodriguez",
    sellerId: 2,
    buyerName: "Jane Doe",
    buyerId: 3,
    initials: "MR",
    type: "selling",
    status: "awaiting_payment",
    statusText: "Awaiting payment",
    flightNumber: "AA 123",
    dateDeparture: "2025-12-16T08:15:00Z",
    dateArrival: "2025-12-17T08:45:00Z",
    departureAirport: "JFK",
    arrivalAirport: "LHR",
    weight: 10,
    pricePerKg: 8,
    total: 80,
    conditions: "No special conditions",
  },
  {
    id: 3,
    sellerName: "Alex Thompson",
    sellerId: 3,
    buyerName: "John Doe",
    buyerId: 4,
    initials: "AT",
    type: "selling",
    status: "waiting_for_response",
    statusText: "Reservation sent",
    flightNumber: "DL 456",
    dateDeparture: "2025-12-20T06:45:00Z",
    dateArrival: "2025-12-20T06:45:00Z",
    departureAirport: "ATL",
    arrivalAirport: "CDG",
    weight: 8,
    pricePerKg: 12,
    total: 96,
    conditions: "No special conditions",
  },
  {
    id: 4,
    sellerName: "Emily Davis",
    sellerId: 4,
    buyerName: "John Doe",
    buyerId: 5,
    initials: "ED",
    type: "buying",
    status: "completed",
    statusText: "Completed",
    flightNumber: "BA 789",
    dateDeparture: "2025-12-10T15:30:00Z",
    dateArrival: "2025-12-10T15:30:00Z",
    departureAirport: "LHR",
    arrivalAirport: "JFK",
    weight: 5,
    pricePerKg: 10,
    total: 50,
    conditions: "No special conditions",
  },
  {
    id: 5,
    sellerName: "John Smith",
    sellerId: 5,
    buyerName: "John Doe",
    buyerId: 6,
    initials: "JS",
    type: "buying",
    status: "payment_required",
    statusText: "Payment required",
    flightNumber: "AF 321",
    dateDeparture: "2025-12-18T10:00:00Z",
    dateArrival: "2025-12-18T10:00:00Z",
    departureAirport: "CDG",
    arrivalAirport: "LAX",
    weight: 7,
    pricePerKg: 9,
    total: 63,
    conditions: "No special conditions",
  },
  {
    id: 6,
    sellerName: "Linda Johnson",
    sellerId: 6,
    buyerName: "John Doe",
    buyerId: 7,
    initials: "LJ",
    type: "selling",
    status: "request_rejected",
    statusText: "Request rejected",
    flightNumber: "LH 654",
    dateDeparture: "2025-12-22T17:15:00Z",
    dateArrival: "2025-12-22T17:15:00Z",
    departureAirport: "FRA",
    arrivalAirport: "ORD",
    weight: 9,
    pricePerKg: 11,
    total: 99,
    conditions: "No special conditions",
  },
  {
    id: 7,
    sellerName: "David Wilson",
    sellerId: 7,
    buyerName: "John Doe",
    buyerId: 8,
    initials: "DW",
    type: "buying",
    status: "browse_listing",
    statusText: "Browsing listings",
    flightNumber: "SQ 888",
    dateDeparture: "2025-12-23T01:10:00Z",
    dateArrival: "2025-12-28T04:55:00Z",
    departureAirport: "SIN",
    arrivalAirport: "SFO",
    weight: 12,
    pricePerKg: 15,
    total: 180,
    conditions: "No special conditions",
  },
  {
    id: 8,
    sellerName: "Sophia Martinez",
    sellerId: 8,
    buyerName: "John Doe",
    buyerId: 9,
    initials: "SM",
    type: "selling",
    status: "cancelled",
    statusText: "Cancelled",
    flightNumber: "QF 12",
    dateDeparture: "2025-12-30T21:45:00Z",
    dateArrival: "2025-12-30T21:45:00Z",
    departureAirport: "SYD",
    arrivalAirport: "LAX",
    weight: 4,
    pricePerKg: 14,
    total: 56,
    conditions: "No special conditions",
  },
  {
    id: 9,
    sellerName: "James Brown",
    sellerId: 9,
    buyerName: "John Doe",
    buyerId: 10,
    initials: "JB",
    type: "buying",
    status: "reservation_received",
    statusText: "Confirmed",
    flightNumber: "EK 202",
    dateDeparture: "2025-12-28T02:30:00Z",
    dateArrival: "2025-12-28T02:30:00Z",
    departureAirport: "DXB",
    arrivalAirport: "JFK",
    weight: 11,
    pricePerKg: 13,
    total: 143,
    conditions: "No special conditions",
  },
];

export default mockTransactions;
