spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/demo_db
spring.datasource.username=monuser
spring.datasource.password=monpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
