spring:
  application:
    name: stripe-service
server:
  port: ${PORT:8082}

eureka:
  instance:
    hostname: stripeservice-app-e0349536e242.herokuapp.com
    prefer-ip-address: false
    non-secure-port: 80
    non-secure-port-enabled: true
    secure-port-enabled: false
    lease-renewal-interval-in-seconds: 10
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://eurekaserver-app-dd87242b5252.herokuapp.com/eureka/
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
    eureka-connection-idle-timeout-seconds: 5

logging:
  level:
    "[com.netflix.eureka]": ERROR
    "[com.netflix.discovery]": ERROR
    root: INFO