services:
  # --- EUREKA SERVER ---
  eureka-server:
    build:
      context: ./eurekaserver
      dockerfile: Dockerfile
    container_name: bagbuddy-eureka-server
    ports:
      - "8761:8761"
    networks:
      - bagbuddy-network

  # --- API GATEWAY ---
  api-gateway:
    build:
      context: ./apigateway
      dockerfile: Dockerfile
    container_name: bagbuddy-api-gateway-dev
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    restart: unless-stopped
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - bagbuddy-network

  # --- TRIP SERVICE ---
  trip-service:
    build:
      context: ./tripservice
      dockerfile: Dockerfile
    container_name: bagbuddy-trip-service-dev
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - tripservice-db
    environment:
      POSTGRES_DB: tripservice
      POSTGRES_USER: tripuser
      POSTGRES_PASSWORD: trippass
    networks:
      - bagbuddy-network

  tripservice-db:
    image: postgres:15-alpine
    container_name: bagbuddy-trip-service-postgres
    environment:
      POSTGRES_DB: tripservice
      POSTGRES_USER: tripuser
      POSTGRES_PASSWORD: trippass
    volumes:
      - trip_pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - bagbuddy-network

  # --- KEYCLOAK ---
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    container_name: bagbuddy-keycloak
    command: start-dev
    environment:
      KC_HTTP_ENABLED: true
      KC_HTTP_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTPS_REQUIRED: false
      KC_HOSTNAME: 100.108.226.114
      KC_HOSTNAME_URL: http://100.108.226.114:8000
      KC_HOSTNAME_ADMIN_URL: http://100.108.226.114:8000
      KC_PROXY: none
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8000:8080"
    depends_on:
      - keycloak-db
    networks:
      - bagbuddy-network

  keycloak-db:
    image: postgres:15-alpine
    container_name: bagbuddy-keycloak-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak_pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - bagbuddy-network

  # --- TRANSACTION SERVICE ---
  transaction-service:
    build:
      context: ./transactionservice
      dockerfile: Dockerfile
    container_name: bagbuddy-transaction-service-dev
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - transactionservice-db
    environment:
      POSTGRES_DB: transactionservice
      POSTGRES_USER: transactionuser
      POSTGRES_PASSWORD: transactionpass
    networks:
      - bagbuddy-network

  transactionservice-db:
    image: postgres:15-alpine
    container_name: bagbuddy-transaction-service-postgres
    environment:
      POSTGRES_DB: transactionservice
      POSTGRES_USER: transactionuser
      POSTGRES_PASSWORD: transactionpass
    volumes:
      - transaction_pgdata:/var/lib/postgresql/data
    ports:
      - "5437:5432"
    networks:
      - bagbuddy-network

  # --- REVIEW SERVICE ---
  review-service:
    build:
      context: ./reviewservice
      dockerfile: Dockerfile
    container_name: bagbuddy-review-service-dev
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - reviewservice-db
    environment:
      POSTGRES_DB: reviewservice
      POSTGRES_USER: reviewuser
      POSTGRES_PASSWORD: reviewpass
    networks:
      - bagbuddy-network

  reviewservice-db:
    image: postgres:15-alpine
    container_name: bagbuddy-review-service-postgres
    environment:
      POSTGRES_DB: reviewservice
      POSTGRES_USER: reviewuser
      POSTGRES_PASSWORD: reviewpass
    volumes:
      - review_pgdata:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    networks:
      - bagbuddy-network

      
  # --- STRIPE SERVICE ---
  review-service:
    build:
      context: ./stripeservice
      dockerfile: Dockerfile
    container_name: bagbuddy-stripe-service-dev
    ports:
      - "8086:8086"
    depends_on:
      - eureka-server
    environment:
      STRIPE_API_KEY: pk_test_51SScISPo3GjutwTcQJ2RsC7kKT5zto7ohJX2qtuGPqNYfBWxchVcYgYiWhK6ogeyNwZiJACzpD1wWhKlpFvOzeIj00OPDJRYBN
    networks:
      - bagbuddy-network

# --- VOLUMES & NETWORK ---
volumes:
  messaging_pgdata:
  transaction_pgdata:
  keycloak_pgdata:
  review_pgdata:
  trip_pgdata:

networks:
  bagbuddy-network:
    driver: bridge
