name: BagBuddy CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-and-test:
    name: Install, Lint, Test & Build
    runs-on: ubuntu-latest

    steps:
      # Récupère le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configure Node
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      # Installe les dépendances
      - name: Install dependencies
        run: npm ci

      # Vérifie TypeScript
      - name: Type check
        run: npx tsc --noEmit

      # Lint
      - name: Run linter
        run: npm run lint

      # Tests unitaires
      - name: Run unit tests
        run: npm test -- --ci

      # Build Expo IOS
      - name: Build Expo IOS
        run: npx expo export --platform ios

      # Build Expo Android
      - name: Build Expo Android
        run: npx expo export --platform android